### ISSUE TITLE
BUG error in compilation

### ISSUE THREAD

**Issue by DiegoMendoza1** [mobizt/Firebase-ESP32#70]
When I compile in Arduino IDE 1.8.12 with the board ESP32 Dev Module it throw this error

`

In file included from C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:43:0:

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.h:606:10: error: 'vector' in namespace 'std' does not name a template type

     std::vector<path_tk_t> _pathTk = std::vector<path_tk_t>();

          ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.h:607:10: error: 'vector' in namespace 'std' does not name a template type

     std::vector<eltk_t> _eltk = std::vector<eltk_t>();

          ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.h:608:10: error: 'vector' in namespace 'std' does not name a template type

     std::vector<el_t> _el = std::vector<el_t>();

          ^

In file included from C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:43:0:

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.h:669:48: error: 'std::vector' has not been declared

     void _strToTk(const std::string &str, std::vector<path_tk_t> &tk, char delim);

                                                ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.h:669:54: error: expected ',' or '...' before '<' token

     void _strToTk(const std::string &str, std::vector<path_tk_t> &tk, char delim);

                                                      ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'FirebaseJson& FirebaseJson::_add(const char*, const char*, size_t, size_t, bool, bool)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:369:27: error: 'strcat_P' was not declared in this scope

         strcat_P(buf, _pr2);

                           ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'bool FirebaseJson::get(FirebaseJsonData&, const String&, bool)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:392:28: error: '_pathTk' was not declared in this scope

     _strToTk(path.c_str(), _pathTk, '/');

                            ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'size_t FirebaseJson::iteratorBegin(const char*)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:429:5: error: '_eltk' was not declared in this scope

     _eltk.clear();

     ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:432:5: error: '_el' was not declared in this scope

     _el.clear();

     ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJson::iteratorEnd()':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:440:5: error: '_eltk' was not declared in this scope

     _eltk.clear();

     ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJson::iteratorGet(size_t, int&, String&, String&)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:452:9: error: '_eltk' was not declared in this scope

     if (_eltk.size() < index + 1)

         ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:460:9: error: '_eltk' was not declared in this scope

     if (_eltk[index].type == 0)

         ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJson::_jsmn_parse(bool)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:500:5: error: '_eltk' was not declared in this scope

     _eltk.clear();

     ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJson::_setMark(int, bool)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:537:28: error: '_el' was not declared in this scope

     for (size_t i = 0; i < _el.size(); i++)

                            ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJson::_setSkip(int, bool)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:549:28: error: '_el' was not declared in this scope

     for (size_t i = 0; i < _el.size(); i++)

                            ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJson::_setRef(int, bool)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:561:28: error: '_el' was not declared in this scope

     for (size_t i = 0; i < _el.size(); i++)

                            ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJson::_getTkIndex(int, tk_index_t&)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:586:28: error: '_el' was not declared in this scope

     for (size_t i = 0; i < _el.size(); i++)

                            ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'bool FirebaseJson::_updateTkIndex(uint16_t, int&, char*, int, char*, PRINT_MODE, bool)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:608:28: error: '_el' was not declared in this scope

     for (size_t i = 0; i < _el.size(); i++)

                            ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:666:65: error: '_pathTk' was not declared in this scope

                                     if (_parseCompleted == (int)_pathTk.size())

                                                                 ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:690:73: error: '_pathTk' was not declared in this scope

                                             if (_parseCompleted == (int)_pathTk.size())

                                                                         ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:706:51: error: '_pathTk' was not declared in this scope

                                 _parseCompleted = _pathTk.size();

                                                   ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'bool FirebaseJson::_updateTkIndex2(std::__cxx11::string&, uint16_t, int&, char*, int, char*, PRINT_MODE)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:739:28: error: '_el' was not declared in this scope

     for (size_t i = 0; i < _el.size(); i++)

                            ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'bool FirebaseJson::_updateTkIndex3(uint16_t, int&, char*, int, PRINT_MODE)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:803:28: error: '_el' was not declared in this scope

     for (size_t i = 0; i < _el.size(); i++)

                            ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJson::_insertChilds(char*, PRINT_MODE)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:868:18: error: '_pathTk' was not declared in this scope

     for (int i = _pathTk.size() - 1; i > _parseCompleted - 1; i--)

                  ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:885:14: error: '_pathTk' was not declared in this scope

     if ((int)_pathTk.size() == _parseCompleted)

              ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJson::_addArrNodes(std::__cxx11::string&, std::__cxx11::string&, int, char*, PRINT_MODE)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:907:31: error: '_pathTk' was not declared in this scope

             if (index == (int)_pathTk.size() - 1)

                               ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJson::_addObjNodes(std::__cxx11::string&, std::__cxx11::string&, int, char*, PRINT_MODE)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:940:12: error: '_pathTk' was not declared in this scope

     str += _pathTk[index].tk.c_str();

            ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJson::_parseToken(uint16_t&, char*, int&, char*, int, PRINT_MODE)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:983:26: error: '_pathTk' was not declared in this scope

                 if ((int)_pathTk.size() != _parseDepth + 1)

                          ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1042:26: error: '_pathTk' was not declared in this scope

                 if ((int)_pathTk.size() != _parseDepth + 1)

                          ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1136:9: error: '_el' was not declared in this scope

         _el.push_back(e);

         ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1178:17: error: '_eltk' was not declared in this scope

                 _eltk.push_back(el);

                 ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1239:17: error: '_eltk' was not declared in this scope

                 _eltk.push_back(el);

                 ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJson::_compileToken(uint16_t&, char*, int&, char*, int, PRINT_MODE, char*, int, bool)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1273:26: error: '_pathTk' was not declared in this scope

                 if ((int)_pathTk.size() != _parseDepth + 1)

                          ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1324:26: error: '_pathTk' was not declared in this scope

                 if ((int)_pathTk.size() != _parseDepth + 1)

                          ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1370:35: error: '_pathTk' was not declared in this scope

                 _parseCompleted = _pathTk.size();

                                   ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1420:9: error: '_el' was not declared in this scope

         _el.push_back(e);

         ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJson::_removeToken(uint16_t&, char*, int&, char*, int, PRINT_MODE, char*, int, bool)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1617:9: error: '_el' was not declared in this scope

         _el.push_back(e);

         ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'single_child_parent_t FirebaseJson::_findSCParent(int)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1743:32: error: '_el' was not declared in this scope

         for (size_t j = 0; j < _el.size(); j++)

                                ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: At global scope:

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1795:58: error: 'std::vector' has not been declared

 void FirebaseJson::_strToTk(const std::string &str, std::vector<path_tk_t> &tk, char delim)

                                                          ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1795:64: error: expected ',' or '...' before '<' token

 void FirebaseJson::_strToTk(const std::string &str, std::vector<path_tk_t> &tk, char delim)

                                                                ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJson::_strToTk(const string&, int)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1798:24: error: 'delim' was not declared in this scope

     current = str.find(delim);

                        ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1808:13: error: 'tk' was not declared in this scope

             tk.push_back(tk_t);

             ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1821:9: error: 'tk' was not declared in this scope

         tk.push_back(tk_t);

         ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJson::_parse(const char*, PRINT_MODE)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1845:20: error: '_pathTk' was not declared in this scope

     _strToTk(path, _pathTk, '/');

                    ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1863:5: error: '_el' was not declared in this scope

     _el.clear();

     ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1864:5: error: '_eltk' was not declared in this scope

     _eltk.clear();

     ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJson::clearPathTk()':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1894:18: error: '_pathTk' was not declared in this scope

     size_t len = _pathTk.size();

                  ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1900:5: error: 'vector' is not a member of 'std'

     std::vector<path_tk_t>().swap(_pathTk);

     ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1900:26: error: expected primary-expression before '>' token

     std::vector<path_tk_t>().swap(_pathTk);

                          ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1900:28: error: expected primary-expression before ')' token

     std::vector<path_tk_t>().swap(_pathTk);

                            ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJson::_parse(const char*, int, int, PRINT_MODE)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1927:58: error: '_pathTk' was not declared in this scope

                 if (_nextDepth > -1 && _nextDepth < (int)_pathTk.size())

                                                          ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:1939:17: error: '_pathTk' was not declared in this scope

                 _pathTk[depth].matched = true;

                 ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'bool FirebaseJson::_isArrTk(int)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:2005:22: error: '_pathTk' was not declared in this scope

     if (index < (int)_pathTk.size())

                      ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'bool FirebaseJson::_isStrTk(int)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:2012:22: error: '_pathTk' was not declared in this scope

     if (index < (int)_pathTk.size())

                      ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'int FirebaseJson::_getArrIndex(int)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:2021:22: error: '_pathTk' was not declared in this scope

     if (index < (int)_pathTk.size())

                      ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJson::_set(const char*, const char*)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:2154:20: error: '_pathTk' was not declared in this scope

     _strToTk(path, _pathTk, '/');

                    ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:2173:5: error: '_el' was not declared in this scope

     _el.clear();

     ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:2174:5: error: '_eltk' was not declared in this scope

     _eltk.clear();

     ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'bool FirebaseJson::remove(const String&)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:2231:28: error: '_pathTk' was not declared in this scope

     _strToTk(path.c_str(), _pathTk, '/');

                            ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:2249:5: error: '_el' was not declared in this scope

     _el.clear();

     ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:2250:5: error: '_eltk' was not declared in this scope

     _eltk.clear();

     ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'bool FirebaseJsonArray::_get(FirebaseJsonData&, const char*)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:2788:41: error: 'class FirebaseJson' has no member named '_pathTk'

     _json._strToTk(path2.c_str(), _json._pathTk, '/');

                                         ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp: In member function 'void FirebaseJsonArray::_set(const char*, const char*, bool)':

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:2920:27: error: 'strcat_P' was not declared in this scope

         strcat_P(tmp2, _qt);

                           ^

C:\Users\dmend\Documents\Arduino\libraries\Firebase_ESP32_Client\src\FirebaseJson.cpp:2925:33: error: 'class FirebaseJson' has no member named '_pathTk'

     _json._strToTk(path2, _json._pathTk, '/');`

**Comment by DiegoMendoza1** [comment]
I have found the issue. The ESP32 board wasn´t correctly installed in Arduino IDE
